-- MySQL Script generated by MySQL Workbench
-- 03/13/15 13:14:33
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Menu`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Menu` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Menu` (
  `idMenu` INT NOT NULL,
  PRIMARY KEY (`idMenu`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Utilisateurs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Utilisateurs` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Utilisateurs` (
  `idUtilisateurs` INT NOT NULL,
  `nom` VARCHAR(15) NULL,
  `mail` VARCHAR(45) NULL,
  `adresse` VARCHAR(45) NULL,
  `mot de passe` VARCHAR(45) NULL,
  `photo` VARCHAR(45) NULL,
  `Pseudo` VARCHAR(45) NULL,
  `telephone` INT NULL,
  `Prénom` VARCHAR(45) NULL,
  PRIMARY KEY (`idUtilisateurs`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`sujet`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`sujet` ;

CREATE TABLE IF NOT EXISTS `mydb`.`sujet` (
  `idsujet` INT NOT NULL,
  `Utilisateurs_idUtilisateurs` INT NOT NULL,
  `texte` VARCHAR(45) NULL,
  PRIMARY KEY (`idsujet`, `Utilisateurs_idUtilisateurs`),
  INDEX `fk_sujet_Utilisateurs1_idx` (`Utilisateurs_idUtilisateurs` ASC),
  CONSTRAINT `fk_sujet_Utilisateurs1`
    FOREIGN KEY (`Utilisateurs_idUtilisateurs`)
    REFERENCES `mydb`.`Utilisateurs` (`idUtilisateurs`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Forum post`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Forum post` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Forum post` (
  `idForum post` INT NOT NULL,
  `Menu_idMenu` INT NOT NULL,
  `texte` TEXT NULL,
  `sujet_idsujet` INT NOT NULL,
  `sujet_Utilisateurs_idUtilisateurs` INT NOT NULL,
  `sujet_Forum post_idForum post` INT NOT NULL,
  PRIMARY KEY (`idForum post`, `sujet_idsujet`, `sujet_Utilisateurs_idUtilisateurs`, `sujet_Forum post_idForum post`),
  INDEX `fk_Forum post_Menu1_idx` (`Menu_idMenu` ASC),
  INDEX `fk_Forum post_sujet1_idx` (`sujet_idsujet` ASC, `sujet_Utilisateurs_idUtilisateurs` ASC, `sujet_Forum post_idForum post` ASC),
  CONSTRAINT `fk_Forum post_Menu1`
    FOREIGN KEY (`Menu_idMenu`)
    REFERENCES `mydb`.`Menu` (`idMenu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Forum post_sujet1`
    FOREIGN KEY (`sujet_idsujet` , `sujet_Utilisateurs_idUtilisateurs`)
    REFERENCES `mydb`.`sujet` (`idsujet` , `Utilisateurs_idUtilisateurs`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Forum reponses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Forum reponses` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Forum reponses` (
  `idForum reponses` INT NOT NULL,
  `texte` TEXT NULL,
  `Forum post_idForum post` INT NOT NULL,
  `Forum post_sujet_idsujet` INT NOT NULL,
  `Forum post_sujet_Utilisateurs_idUtilisateurs` INT NOT NULL,
  `Forum post_sujet_Forum post_idForum post` INT NOT NULL,
  PRIMARY KEY (`idForum reponses`, `Forum post_idForum post`, `Forum post_sujet_idsujet`, `Forum post_sujet_Utilisateurs_idUtilisateurs`, `Forum post_sujet_Forum post_idForum post`),
  INDEX `fk_Forum reponses_Forum post1_idx` (`Forum post_idForum post` ASC, `Forum post_sujet_idsujet` ASC, `Forum post_sujet_Utilisateurs_idUtilisateurs` ASC, `Forum post_sujet_Forum post_idForum post` ASC),
  CONSTRAINT `fk_Forum reponses_Forum post1`
    FOREIGN KEY (`Forum post_idForum post` , `Forum post_sujet_idsujet` , `Forum post_sujet_Utilisateurs_idUtilisateurs` , `Forum post_sujet_Forum post_idForum post`)
    REFERENCES `mydb`.`Forum post` (`idForum post` , `sujet_idsujet` , `sujet_Utilisateurs_idUtilisateurs` , `sujet_Forum post_idForum post`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Régions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Régions` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Régions` (
  `idRégions` INT NOT NULL,
  `code postal` VARCHAR(45) NULL,
  `Utilisateurs_idUtilisateurs1` INT NOT NULL,
  PRIMARY KEY (`idRégions`, `Utilisateurs_idUtilisateurs1`),
  INDEX `fk_Régions_Utilisateurs2_idx` (`Utilisateurs_idUtilisateurs1` ASC),
  CONSTRAINT `fk_Régions_Utilisateurs2`
    FOREIGN KEY (`Utilisateurs_idUtilisateurs1`)
    REFERENCES `mydb`.`Utilisateurs` (`idUtilisateurs`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Transactions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Transactions` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Transactions` (
  `idTransactions` INT NOT NULL,
  `date` DATETIME NULL,
  `type` VARCHAR(45) NULL,
  `Quantité` INT NULL,
  `Etat transaction` VARCHAR(45) NULL,
  `Régions_idRégions1` INT NOT NULL,
  `Utilisateurs_idUtilisateurs` INT NOT NULL,
  PRIMARY KEY (`idTransactions`, `Régions_idRégions1`, `Utilisateurs_idUtilisateurs`),
  UNIQUE INDEX `idTransactions_UNIQUE` (`idTransactions` ASC),
  INDEX `fk_Transactions_Régions2_idx` (`Régions_idRégions1` ASC),
  INDEX `fk_Transactions_Utilisateurs2_idx` (`Utilisateurs_idUtilisateurs` ASC),
  CONSTRAINT `fk_Transactions_Régions2`
    FOREIGN KEY (`Régions_idRégions1`)
    REFERENCES `mydb`.`Régions` (`idRégions`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Transactions_Utilisateurs2`
    FOREIGN KEY (`Utilisateurs_idUtilisateurs`)
    REFERENCES `mydb`.`Utilisateurs` (`idUtilisateurs`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Catégories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Catégories` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Catégories` (
  `idCatégories` INT NOT NULL,
  `Type` VARCHAR(45) NULL,
  PRIMARY KEY (`idCatégories`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Produit`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Produit` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Produit` (
  `idProduit` INT NOT NULL,
  `Catégories_idCatégories` INT NOT NULL,
  PRIMARY KEY (`idProduit`, `Catégories_idCatégories`),
  INDEX `fk_Produit_Catégories1_idx` (`Catégories_idCatégories` ASC),
  CONSTRAINT `fk_Produit_Catégories1`
    FOREIGN KEY (`Catégories_idCatégories`)
    REFERENCES `mydb`.`Catégories` (`idCatégories`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Produits en ligne`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Produits en ligne` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Produits en ligne` (
  `idProduits` INT NOT NULL,
  `Nom` VARCHAR(15) NULL,
  `Quantitée` FLOAT NULL,
  `Prix` FLOAT NULL,
  `Decription` TEXT NULL,
  `date` DATETIME NULL,
  `Photo` VARCHAR(45) NULL,
  `Type` VARCHAR(45) NULL,
  `Transactions_idTransactions1` INT NOT NULL,
  `Utilisateurs_idUtilisateurs` INT NOT NULL,
  `Produit_idProduit` INT NOT NULL,
  PRIMARY KEY (`idProduits`, `Transactions_idTransactions1`, `Utilisateurs_idUtilisateurs`, `Produit_idProduit`),
  INDEX `fk_Produits_Transactions2_idx` (`Transactions_idTransactions1` ASC),
  INDEX `fk_Produits_Utilisateurs1_idx` (`Utilisateurs_idUtilisateurs` ASC),
  INDEX `fk_Produits en ligne_Produit1_idx` (`Produit_idProduit` ASC),
  CONSTRAINT `fk_Produits_Transactions2`
    FOREIGN KEY (`Transactions_idTransactions1`)
    REFERENCES `mydb`.`Transactions` (`idTransactions`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Produits_Utilisateurs1`
    FOREIGN KEY (`Utilisateurs_idUtilisateurs`)
    REFERENCES `mydb`.`Utilisateurs` (`idUtilisateurs`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Produits en ligne_Produit1`
    FOREIGN KEY (`Produit_idProduit`)
    REFERENCES `mydb`.`Produit` (`idProduit`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Sous catégories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Sous catégories` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Sous catégories` (
  `idSous catégories` INT NOT NULL,
  `Catégories_idCatégories` INT NOT NULL,
  PRIMARY KEY (`idSous catégories`),
  INDEX `fk_Sous catégories_Catégories1_idx` (`Catégories_idCatégories` ASC),
  CONSTRAINT `fk_Sous catégories_Catégories1`
    FOREIGN KEY (`Catégories_idCatégories`)
    REFERENCES `mydb`.`Catégories` (`idCatégories`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Recettes post`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Recettes post` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Recettes post` (
  `idRecettes post` INT NOT NULL,
  `texte` TEXT NULL,
  `Produits_idProduits` INT NOT NULL,
  `Produits_Catégories_idCatégories` INT NOT NULL,
  `Utilisateurs_idUtilisateurs1` INT NOT NULL,
  PRIMARY KEY (`idRecettes post`, `Produits_idProduits`, `Produits_Catégories_idCatégories`, `Utilisateurs_idUtilisateurs1`),
  INDEX `fk_Recettes post_Produits1_idx` (`Produits_idProduits` ASC, `Produits_Catégories_idCatégories` ASC),
  INDEX `fk_Recettes post_Utilisateurs2_idx` (`Utilisateurs_idUtilisateurs1` ASC),
  CONSTRAINT `fk_Recettes post_Produits1`
    FOREIGN KEY (`Produits_idProduits`)
    REFERENCES `mydb`.`Produits en ligne` (`idProduits`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Recettes post_Utilisateurs2`
    FOREIGN KEY (`Utilisateurs_idUtilisateurs1`)
    REFERENCES `mydb`.`Utilisateurs` (`idUtilisateurs`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Recette commentaires`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Recette commentaires` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Recette commentaires` (
  `idRecette` INT NOT NULL,
  `Menu_idMenu` INT NOT NULL,
  `texte` TEXT NULL,
  `Utilisateurs_idUtilisateurs1` INT NOT NULL,
  `Recettes post_idRecettes post` INT NOT NULL,
  `Recettes post_Produits_idProduits` INT NOT NULL,
  `Recettes post_Produits_Catégories_idCatégories` INT NOT NULL,
  `Recettes post_Utilisateurs_idUtilisateurs1` INT NOT NULL,
  PRIMARY KEY (`idRecette`, `Utilisateurs_idUtilisateurs1`, `Recettes post_idRecettes post`, `Recettes post_Produits_idProduits`, `Recettes post_Produits_Catégories_idCatégories`, `Recettes post_Utilisateurs_idUtilisateurs1`),
  INDEX `fk_Recette_Menu1_idx` (`Menu_idMenu` ASC),
  INDEX `fk_Recette commentaires_Utilisateurs1_idx` (`Utilisateurs_idUtilisateurs1` ASC),
  INDEX `fk_Recette commentaires_Recettes post1_idx` (`Recettes post_idRecettes post` ASC, `Recettes post_Produits_idProduits` ASC, `Recettes post_Produits_Catégories_idCatégories` ASC, `Recettes post_Utilisateurs_idUtilisateurs1` ASC),
  CONSTRAINT `fk_Recette_Menu1`
    FOREIGN KEY (`Menu_idMenu`)
    REFERENCES `mydb`.`Menu` (`idMenu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Recette commentaires_Utilisateurs1`
    FOREIGN KEY (`Utilisateurs_idUtilisateurs1`)
    REFERENCES `mydb`.`Utilisateurs` (`idUtilisateurs`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Recette commentaires_Recettes post1`
    FOREIGN KEY (`Recettes post_idRecettes post` , `Recettes post_Produits_idProduits` , `Recettes post_Produits_Catégories_idCatégories` , `Recettes post_Utilisateurs_idUtilisateurs1`)
    REFERENCES `mydb`.`Recettes post` (`idRecettes post` , `Produits_idProduits` , `Produits_Catégories_idCatégories` , `Utilisateurs_idUtilisateurs1`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`table1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`table1` ;

CREATE TABLE IF NOT EXISTS `mydb`.`table1` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Transactions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Transactions` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Transactions` (
  `idTransactions` INT NOT NULL,
  `date` DATETIME NULL,
  `type` VARCHAR(45) NULL,
  `Quantité` INT NULL,
  `Etat transaction` VARCHAR(45) NULL,
  `Régions_idRégions1` INT NOT NULL,
  `Utilisateurs_idUtilisateurs` INT NOT NULL,
  PRIMARY KEY (`idTransactions`, `Régions_idRégions1`, `Utilisateurs_idUtilisateurs`),
  UNIQUE INDEX `idTransactions_UNIQUE` (`idTransactions` ASC),
  INDEX `fk_Transactions_Régions2_idx` (`Régions_idRégions1` ASC),
  INDEX `fk_Transactions_Utilisateurs2_idx` (`Utilisateurs_idUtilisateurs` ASC),
  CONSTRAINT `fk_Transactions_Régions2`
    FOREIGN KEY (`Régions_idRégions1`)
    REFERENCES `mydb`.`Régions` (`idRégions`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Transactions_Utilisateurs2`
    FOREIGN KEY (`Utilisateurs_idUtilisateurs`)
    REFERENCES `mydb`.`Utilisateurs` (`idUtilisateurs`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Panier`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Panier` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Panier` (
  `idPanier` INT NOT NULL,
  `Utilisateurs_idUtilisateurs` INT NOT NULL,
  `Produits_idProduits` INT NOT NULL,
  `` VARCHAR(45) NULL,
  PRIMARY KEY (`idPanier`),
  INDEX `fk_Panier_Utilisateurs1_idx` (`Utilisateurs_idUtilisateurs` ASC),
  INDEX `fk_Panier_Produits1_idx` (`Produits_idProduits` ASC),
  CONSTRAINT `fk_Panier_Utilisateurs1`
    FOREIGN KEY (`Utilisateurs_idUtilisateurs`)
    REFERENCES `mydb`.`Utilisateurs` (`idUtilisateurs`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Panier_Produits1`
    FOREIGN KEY (`Produits_idProduits`)
    REFERENCES `mydb`.`Produits en ligne` (`idProduits`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`essaie`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`essaie` ;

CREATE TABLE IF NOT EXISTS `mydb`.`essaie` (
  `texte` INT NOT NULL,
  PRIMARY KEY (`texte`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Produits_has_Recettes post`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Produits_has_Recettes post` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Produits_has_Recettes post` (
  `Produits_idProduits` INT NOT NULL,
  `Produits_Catégories_idCatégories` INT NOT NULL,
  `Recettes post_idRecettes post` INT NOT NULL,
  `Recettes post_Produits_idProduits` INT NOT NULL,
  `Recettes post_Produits_Catégories_idCatégories` INT NOT NULL,
  PRIMARY KEY (`Produits_idProduits`, `Produits_Catégories_idCatégories`, `Recettes post_idRecettes post`, `Recettes post_Produits_idProduits`, `Recettes post_Produits_Catégories_idCatégories`),
  INDEX `fk_Produits_has_Recettes post_Recettes post1_idx` (`Recettes post_idRecettes post` ASC, `Recettes post_Produits_idProduits` ASC, `Recettes post_Produits_Catégories_idCatégories` ASC),
  INDEX `fk_Produits_has_Recettes post_Produits1_idx` (`Produits_idProduits` ASC, `Produits_Catégories_idCatégories` ASC),
  CONSTRAINT `fk_Produits_has_Recettes post_Produits1`
    FOREIGN KEY (`Produits_idProduits`)
    REFERENCES `mydb`.`Produits en ligne` (`idProduits`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Produits_has_Recettes post_Recettes post1`
    FOREIGN KEY (`Recettes post_idRecettes post` , `Recettes post_Produits_idProduits` , `Recettes post_Produits_Catégories_idCatégories`)
    REFERENCES `mydb`.`Recettes post` (`idRecettes post` , `Produits_idProduits` , `Produits_Catégories_idCatégories`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Produits_has_Recettes post1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Produits_has_Recettes post1` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Produits_has_Recettes post1` (
  `Produits_idProduits` INT NOT NULL,
  `Recettes post_idRecettes post` INT NOT NULL,
  `Recettes post_Produits_idProduits` INT NOT NULL,
  `Recettes post_Produits_Catégories_idCatégories` INT NOT NULL,
  PRIMARY KEY (`Produits_idProduits`, `Recettes post_idRecettes post`, `Recettes post_Produits_idProduits`, `Recettes post_Produits_Catégories_idCatégories`),
  INDEX `fk_Produits_has_Recettes post1_Recettes post1_idx` (`Recettes post_idRecettes post` ASC, `Recettes post_Produits_idProduits` ASC, `Recettes post_Produits_Catégories_idCatégories` ASC),
  INDEX `fk_Produits_has_Recettes post1_Produits1_idx` (`Produits_idProduits` ASC),
  CONSTRAINT `fk_Produits_has_Recettes post1_Produits1`
    FOREIGN KEY (`Produits_idProduits`)
    REFERENCES `mydb`.`Produits en ligne` (`idProduits`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Produits_has_Recettes post1_Recettes post1`
    FOREIGN KEY (`Recettes post_idRecettes post` , `Recettes post_Produits_idProduits` , `Recettes post_Produits_Catégories_idCatégories`)
    REFERENCES `mydb`.`Recettes post` (`idRecettes post` , `Produits_idProduits` , `Produits_Catégories_idCatégories`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`commentaires`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`commentaires` ;

CREATE TABLE IF NOT EXISTS `mydb`.`commentaires` (
  `idcommentaires` INT NOT NULL,
  `texte` TEXT NULL,
  `Utilisateurs_idUtilisateurs_commenté` INT NOT NULL,
  `Utilisateurs_idUtilisateurs_commentateur` INT NOT NULL,
  PRIMARY KEY (`idcommentaires`, `Utilisateurs_idUtilisateurs_commenté`, `Utilisateurs_idUtilisateurs_commentateur`),
  INDEX `fk_commentaires_Utilisateurs1_idx` (`Utilisateurs_idUtilisateurs_commenté` ASC),
  INDEX `fk_commentaires_Utilisateurs2_idx` (`Utilisateurs_idUtilisateurs_commentateur` ASC),
  CONSTRAINT `fk_commentaires_Utilisateurs1`
    FOREIGN KEY (`Utilisateurs_idUtilisateurs_commenté`)
    REFERENCES `mydb`.`Utilisateurs` (`idUtilisateurs`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_commentaires_Utilisateurs2`
    FOREIGN KEY (`Utilisateurs_idUtilisateurs_commentateur`)
    REFERENCES `mydb`.`Utilisateurs` (`idUtilisateurs`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`A commentaire et un commenté`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`A commentaire et un commenté` ;

CREATE TABLE IF NOT EXISTS `mydb`.`A commentaire et un commenté` (
  `Utilisateurs_idUtilisateurs` INT NOT NULL,
  `commentaires_idcommentaires` INT NOT NULL,
  `commentaires_Utilisateurs_idUtilisateurs` INT NOT NULL,
  PRIMARY KEY (`Utilisateurs_idUtilisateurs`, `commentaires_idcommentaires`, `commentaires_Utilisateurs_idUtilisateurs`),
  INDEX `fk_Utilisateurs_has_commentaires_commentaires1_idx` (`commentaires_idcommentaires` ASC, `commentaires_Utilisateurs_idUtilisateurs` ASC),
  INDEX `fk_Utilisateurs_has_commentaires_Utilisateurs1_idx` (`Utilisateurs_idUtilisateurs` ASC),
  CONSTRAINT `fk_Utilisateurs_has_commentaires_Utilisateurs1`
    FOREIGN KEY (`Utilisateurs_idUtilisateurs`)
    REFERENCES `mydb`.`Utilisateurs` (`idUtilisateurs`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Utilisateurs_has_commentaires_commentaires1`
    FOREIGN KEY (`commentaires_idcommentaires`)
    REFERENCES `mydb`.`commentaires` (`idcommentaires`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`plusieurs recettes utilisent plusieurs produits`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`plusieurs recettes utilisent plusieurs produits` ;

CREATE TABLE IF NOT EXISTS `mydb`.`plusieurs recettes utilisent plusieurs produits` (
  `Produits_idProduits` INT NOT NULL,
  `Produits_Catégories_idCatégories` INT NOT NULL,
  `Recettes post_idRecettes post` INT NOT NULL,
  `Recettes post_Produits_idProduits` INT NOT NULL,
  `Recettes post_Produits_Catégories_idCatégories` INT NOT NULL,
  PRIMARY KEY (`Produits_idProduits`, `Produits_Catégories_idCatégories`, `Recettes post_idRecettes post`, `Recettes post_Produits_idProduits`, `Recettes post_Produits_Catégories_idCatégories`),
  INDEX `fk_Produits_has_Recettes post2_Recettes post1_idx` (`Recettes post_idRecettes post` ASC, `Recettes post_Produits_idProduits` ASC, `Recettes post_Produits_Catégories_idCatégories` ASC),
  INDEX `fk_Produits_has_Recettes post2_Produits1_idx` (`Produits_idProduits` ASC, `Produits_Catégories_idCatégories` ASC),
  CONSTRAINT `fk_Produits_has_Recettes post2_Produits1`
    FOREIGN KEY (`Produits_idProduits`)
    REFERENCES `mydb`.`Produits en ligne` (`idProduits`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Produits_has_Recettes post2_Recettes post1`
    FOREIGN KEY (`Recettes post_idRecettes post` , `Recettes post_Produits_idProduits` , `Recettes post_Produits_Catégories_idCatégories`)
    REFERENCES `mydb`.`Recettes post` (`idRecettes post` , `Produits_idProduits` , `Produits_Catégories_idCatégories`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
